# name: Publish To Github Page

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# permissions:
#   contents: write

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
#         with:
#           persist-credentials: false

#       - name: Use Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '18.x'

#       - name: Install and Build # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
#         run: |
#           yarn
#           yarn build

#       - name: Generate 404 Page # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
#         run: |
#           echo "<!DOCTYPE html>" > docs/404.html
#           echo "<html>" >> docs/404.html
#           echo "  <head>" >> docs/404.html
#           echo "    <title>Redirecting...</title>" >> docs/404.html
#           echo "    <script>" >> docs/404.html
#           echo "      const path = location.pathname;" >> docs/404.html
#           echo "      const pos = path.indexOf('\/', 1);" >> docs/404.html
#           echo "      const repo = path.substring(0, pos);" >> docs/404.html
#           echo "      const ghpage = path.substring(pos);" >> docs/404.html
#           echo "      const redirectUrl = location.origin+repo+'/?ghpage='+encodeURIComponent(ghpage+location.search);" >> docs/404.html
#           echo "      window.location.replace(redirectUrl);" >> docs/404.html
#           echo "    </script>" >> docs/404.html
#           echo "  </head>" >> docs/404.html
#           echo "  <body>" >> docs/404.html
#           echo "    Redirecting..." >> docs/404.html
#           echo "  </body>" >> docs/404.html
#           echo "</html>" >> docs/404.html

#       - name: Deploy
#         uses: JamesIves/github-pages-deploy-action@v4.3.3
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           BRANCH: release # The branch the action should deploy to.
#           FOLDER: docs # The folder the action should deploy.
